#!/bin/bash
this=$(basename $0)
templates=~/dotfiles
backups=~/dotfiles/.old

pushd .
cd $templates
git pull
popd

mkdir -p $backups
for file in $templates/*; do
    template=$(basename $file)
    if [ "$template" != "$this" ]; then
        homefile=~/.$template
	if [ -L "$homefile" ]; then
		rm "$homefile"
	elif [ -f "$homefile" ] || [ -d "$homefile" ]; then 
		echo "Moving $homefile to $backups ..."
		mv $homefile $backups
        fi
        echo "Creating symlink from $homefile -> $template ..."
        ln -s $templates/$template $homefile 
    fi
done
echo "Update complete"
